dist: trusty
sudo: false

language: d
os:
 - linux
 #- osx
d:
 - dmd
 #- dmd-beta
 #- dmd-nightly
 - ldc
 #- ldc-beta

script:
 - dub build --build=release --compiler=${DC}
 - dub test --compiler=${DC}
